# Menu Configuration for the Alpha Theme
# This file defines menu entries for the site's default language.
#
# Menus supported:
#   - main
#   - main_secondary
#   - main_social
#   - footer
#   - footer_social
#   - sc_social
#
# For multilingual setups, create equivalent files using the language code.
# Example: `menus.fr.toml` for the French version.
#
# Documentation:
# - Menus: https://alpha.oxypteros.com/docs/config/menus-toml/
# - Multilingual: https://alpha.oxypteros.com/docs/multilingual/
# - Shortcodes: https://alpha.oxypteros.com/docs/shortcodes/social/

# Main Menu
[[main]]        
  name = "home"
  url = "/"
  weight = 90

[[main]]        
  name = "curriculum vitae"
  url = "https://tomkonig.com"
  weight = 100

[[main]]        
  name = "more links & contact"
  url = "https://links.tomkonig.com"
  weight = 120 

# Main Secondary
#[[main_secondary]]
#  name = "About Me"
#  url = "/about/"
#  weight = 100

[[main_secondary]]
#  name = "Policy"
#  url = "/policy/"
#  weight = 110

# Main Social
[[main_social]]
  name = "Github"
  url = "https://github.com/TomKonig/"
  pre = "#github"  # Renders a specific icon. See docs for available icons.
  weight = 100

[[main_social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/tkonig"
  pre = "#linkedin" # Renders a specific icon. See docs for available icons.
  weight = 100

# Footer Menu
[[footer]]
name = "CV"
 url = "https://tomkonig.com"
 weight = 100

[[footer]]
name = "intelfy"
 url = "https://intelfy.dk"
 weight = 100

[[footer]]
name = "more links"
 url = "https://links.tomkonig.com"
 weight = 100

# Footer Social
#[[footer_social]]
#  name = "X"
#  url = "https://x.com/your-username"
#  pre = "#twitter" # Renders a specific icon. See docs for available icons.
#  weight = 100

[[footer_social]]
  name = "Github"
  url = "https://github.com/TomKonig"
  pre = "#github"  # Renders a specific icon. See docs for available icons.
  weight = 110

[[footer_social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/tkonig"
  pre = "#linkedin" # Renders a specific icon. See docs for available icons.
  weight = 100

# Shortcode Social
[[sc_social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/tkonig"
  pre = "#linkedin" # Renders a specific icon. See docs for available icons.
  weight = 100

[[sc_social]]
  name = "Github"
  url = "https://github.com/TomKonig"
  pre = "#github" # Renders a specific icon. See docs for available icons.
  weight = 100
