# Root Hugo Configuration
#
# For theme-specific settings, see: `config/_default/`
# Documentation: https://alpha.oxypteros.com/docs/config/hugo-toml

baseURL = "https://blog.tomkonig.com" # Replace with production URL
title = "Tom Konig | blog"
theme = "alpha"
#timeZone = "Europe/Rome"

[module]
  [[module.imports]]
    path = 'https://github.com/hugomods/umami-analytics'

[params]
  [params.services]
    [params.services.umami_analytics]
      id = 'e8aa132e-faea-4308-9708-9f21cb5a0850'
      script_url = 'https://cloud.umami.is/script.js'

# Tailwind Integration (Build Options) 
# Note: Enable the following only if you are using Tailwind CSS with this 
# project.
# For setup instructions, see:
# https://alpha.oxypteros.com/docs/developing-alpha/tailwind

#[build]
#  [build.buildStats]
#    enable = true
#  [[build.cachebusters]]
#    source = 'assets/notwatching/hugo_stats\.json'
#    target = 'css'
#  [[build.cachebusters]]
#    source = '(postcss|tailwind)\.config\.js'
#    target = 'css'
#  [[module.mounts]]
#    source = 'assets'
#    target = 'assets'
#  [[module.mounts]]
#    disableWatch = true
#    source = 'hugo_stats.json'
#    target = 'assets/notwatching/hugo_stats.json'
